apiVersion: storage.k8s.io/v1beta1
kind: StorageClass  
metadata:
  name: heketi  
provisioner: kubernetes.io/glusterfs   
parameters:
  resturl: "http://master-1.openshift.rclsilver.net:8080"  
  restuser: "admin"  
  restuserkey: "admin"
