apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p2p-torrents
  namespace: downloads
  annotations:
    volume.beta.kubernetes.io/storage-class: heketi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
