apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p2p-incoming
  namespace: downloads
  annotations:
    volume.beta.kubernetes.io/storage-class: heketi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
